### ISSUE TITLE
UITestException: The Coded UI Test is running in Single Thread Apartment (STA) mode of COM.  In this mode, all the playback calls should happen from the TestMethod thread only and UITestControl should not be shared across TestMethods.

### ISSUE THREAD

**Issue by icnocop** [dpiessens/specbind#111]
**Environment**
Windows 7 Enterprise x64 SP1
Visual Studio 2015 Update 2
C# Coded UI Test project targeting .NET 4.5 and "Any CPU" platform
SpecFlow 2.0.0
SpecFlow.MsTest 2.0.0
SpecBind 1.7.2.276
SpecBind.CodedUI 1.7.2.276

**Login.feature**

```
Scenario: Log in as admin
    Given I navigated to the Index page
    When I enter data
     | Field     | Value |
     | User Name | admin |
     | Password  | admin |
    And I choose Login
    And I wait for the Dashboard page
    Then I am on the Dashboard page
```

**IndexPage.cs**

```
    [PageNavigation("/index.html")]
    [PageAlias("Login")]
    public class IndexPage : HtmlDocument
    {
        public IndexPage(UITestControl parent)
            : base(parent)
        {
        }

        [ElementLocator(Id = "userName")]
        public HtmlEdit Username { get; set; }

        [ElementLocator(Id = "userPass")]
        public HtmlEdit Password { get; set; }

        [ElementLocator(Id = "btnLogin")]
        public HtmlButton Login { get; set; }
    }
```

**HomePage.cs**

```
    [PageNavigation("/home.html")]
    [PageAlias("Dashboard")]
    public class HomePage : HtmlDocument
    {
        public HomePage(UITestControl parent)
            : base(parent)
        {
        }

        [ElementLocator(Id = "logout")]
        public HtmlHyperlink Logout { get; set; }
    }
```

**App.config**

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <section name="specFlow" type="TechTalk.SpecFlow.Configuration.ConfigurationSectionHandler, TechTalk.SpecFlow"/>
    <section name="specBind" type="SpecBind.Configuration.ConfigurationSectionHandler, SpecBind"/>
  </configSections>
  <specFlow>
    <stepAssemblies>
      <stepAssembly assembly="SpecBind"/>
    </stepAssemblies>
    <unitTestProvider name="MsTest"/>
    <plugins>
      <add name="SpecBindGeneratorPlugin" type="Generator"/>
    </plugins>
  </specFlow>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5"/>
  </startup>
  <specBind>
    <browserFactory provider="SpecBind.CodedUI.CodedUIBrowserFactory, SpecBind.CodedUI" browserType="IE" ensureCleanSession="true"/>
    <application startUrl="http://localhost/Project" />
  </specBind>
</configuration>
```

**Standard Output**

```
Test Name:  LogInAsAdmin
Test Outcome:   Failed
Result Message: 
Test method Project.Specs.LoginFeature.LogInAsAdmin threw exception: 
System.AggregateException: One or more errors occurred. ---> Microsoft.VisualStudio.TestTools.UITest.Extension.UITestException: The Coded UI Test is running in Single Thread Apartment (STA) mode of COM.  In this mode, all the playback calls should happen from the TestMethod thread only and UITestControl should not be shared across TestMethods.
Result StandardOutput:  
Given I navigated to the Index page
SpecBind Debug: Navigation action detected, checking for cookie...
SpecBind Debug: Navigating to page: Index (Project.Specs.IndexPage)
Application Base URI: http://localhost/Project
SpecBind Debug: Navigating to URL: http://localhost/Project/index.html
-> done: PageNavigationSteps.GivenNavigateToPageStep("Index") (4.1s)
When I enter data
  --- table step argument ---
  | Field     | Value |
  | User Name | admin |
  | Password  | admin |
-> done: DataSteps.WhenIEnterDataInFieldsStep(<table>) (2.0s)
And I choose Login
-> done: SelectionSteps.WhenIChooseALinkStep("Login") (1.1s)
And I wait for the Dashboard page
-> error: One or more errors occurred.
Then I am on the Dashboard page
-> skipped because of previous errors
Created Error Screenshot: C:\Working\dev\Project\TestResults\username_hostname 2016-06-03 11_20_23\Out\error_Login_LogInAsAdmin_20160603_112033.jpg
```

**Test Result**

```
Test Name:  LogInAsAdmin
Test FullName:  TestProject.Specs.LoginFeature.LogInAsAdmin
Test Source:    C:\Working\dev\Project.Specs\Login.feature : line 6
Test Outcome:   Failed
Test Duration:  0:00:13.2835088

Result StackTrace:  
at Microsoft.VisualStudio.TestTools.UITest.Playback.ThreadUtility.ThrowExceptionIfCrossThreadAccess(IRPFPlayback playback, IScreenElement uiElement)
   at Microsoft.VisualStudio.TestTools.UITest.Playback.ScreenElement.get_Playback()
   at Microsoft.VisualStudio.TestTools.UITest.Playback.ScreenElement.FromNativeElement(Object nativeElement, String technologyName)
   at Microsoft.VisualStudio.TestTools.UITest.Playback.ScreenElement.FromTechnologyElementInternal(IUITechnologyElement technologyElement)
   at Microsoft.VisualStudio.TestTools.UITest.Playback.ScreenElement.FromTechnologyElement(IUITechnologyElement element)
   at Microsoft.VisualStudio.TestTools.UITesting.UITestControl..ctor(IUITechnologyElement element, UITestControl searchContainer, String queryIdForRefetch)
   at Microsoft.VisualStudio.TestTools.UITesting.BrowserWindow.<GetCurrentDocumentWindowPrivate>b__47_0()
   at Microsoft.VisualStudio.TestTools.UITesting.BrowserWindow.PerformBrowserServiceAction(Func`1 function, String playbackContext)
   at Microsoft.VisualStudio.TestTools.UITesting.BrowserWindow.GetCurrentDocumentWindowPrivate()
   at Microsoft.VisualStudio.TestTools.UITesting.BrowserWindow.<get_CurrentDocumentWindow>b__17_0()
   at Microsoft.VisualStudio.TestTools.UITesting.CodedUITestMethodInvoker.InvokeMethod[T](Func`1 function, UITestControl control, Boolean firePlaybackErrorEvent, Boolean logAsAction)
   at Microsoft.VisualStudio.TestTools.UITesting.BrowserWindow.get_CurrentDocumentWindow()
   at Microsoft.VisualStudio.TestTools.UITesting.SearchHelper.GetUITestControlRecursive(Boolean useCache, Boolean alwaysSearch, ISearchArgument searchArg, IList`1 windowTitles, Int32& timeLeft)
   at Microsoft.VisualStudio.TestTools.UITesting.SearchHelper.GetElement(Boolean useCache, ISearchArgument searchArg)
   at Microsoft.VisualStudio.TestTools.UITesting.SearchHelper.Search(ISearchArgument searchArg)
   at Microsoft.VisualStudio.TestTools.UITesting.UITestControl.FindInternal()
   at Microsoft.VisualStudio.TestTools.UITesting.UITestControl.<Find>b__175_0()
   at Microsoft.VisualStudio.TestTools.UITesting.CodedUITestMethodInvoker.InvokeMethod[T](Func`1 function, UITestControl control, Boolean firePlaybackErrorEvent, Boolean logAsAction)
   at Microsoft.VisualStudio.TestTools.UITesting.UITestControl.Find()
   at Microsoft.VisualStudio.TestTools.UITesting.UITestControl.GetPropertyPrivate(String propertyName)
   at Microsoft.VisualStudio.TestTools.UITesting.UITestControl.<>c__DisplayClass179_0.<GetProperty>b__0()
   at Microsoft.VisualStudio.TestTools.UITesting.CodedUITestMethodInvoker.InvokeMethod[T](Func`1 function, UITestControl control, Boolean firePlaybackErrorEvent, Boolean logAsAction)
   at Microsoft.VisualStudio.TestTools.UITesting.UITestControl.GetProperty(String propertyName)
   at Microsoft.VisualStudio.TestTools.UITesting.HtmlControls.HtmlDocument.get_FrameDocument()
   at SpecBind.CodedUI.CodedUIBrowser.GetNativePageLocation(IPage page)
   at SpecBind.BrowserSupport.BrowserBase.CheckIsOnPage(Type pageType, IPage page, String& actualPath, String& expectedPath)
   at SpecBind.BrowserSupport.BrowserBase.EnsureOnPage(IPage page)
   at SpecBind.Actions.WaitForPageAction.CheckForPage(Type pageType, CancellationToken token)
   at SpecBind.Actions.WaitForPageAction.<>c__DisplayClass9_0.<Execute>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
 --- End of inner exception stack trace ---
    at SpecBind.ActionPipeline.ActionResultExtensions.CheckActionResult(ActionResult result)
   at SpecBind.ActionPipeline.ActionResultExtensions.CheckResult[T](ActionResult result)
   at SpecBind.PageNavigationSteps.CallWaitForPageAction(String pageName, Nullable`1 timeout)
   at SpecBind.PageNavigationSteps.WaitForPageStepWithTimeout(Int32 seconds, String pageName)
   at lambda_method(Closure , IContextManager , Int32 , String )
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at TechTalk.SpecFlow.TestRunner.CollectScenarioErrors()
   at Project.Specs.LoginFeature.ScenarioCleanup()
   at Project.Specs.LoginFeature.LogInAsAdmin() in C:\Working\dev\Project.Web.Specs\Login.feature:line 14
Result Message: 
Test method Project.Specs.LoginFeature.LogInAsAdmin threw exception: 
System.AggregateException: One or more errors occurred. ---> Microsoft.VisualStudio.TestTools.UITest.Extension.UITestException: The Coded UI Test is running in Single Thread Apartment (STA) mode of COM.  In this mode, all the playback calls should happen from the TestMethod thread only and UITestControl should not be shared across TestMethods.
```

Related issue #72 and possibly #78 .

The exception is thrown only after a failed previous test run.

For example, in a previous test run I had `And I wait 10 seconds for the Dashboard page` and it failed:

```
Result StackTrace:  
at SpecBind.ActionPipeline.ActionResultExtensions.CheckActionResult(ActionResult result)
   at SpecBind.ActionPipeline.ActionResultExtensions.CheckResult[T](ActionResult result)
   at SpecBind.PageNavigationSteps.CallWaitForPageAction(String pageName, Nullable`1 timeout)
   at SpecBind.PageNavigationSteps.WaitForPageStepWithTimeout(Int32 seconds, String pageName)
   at lambda_method(Closure , IContextManager , Int32 , String )
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at TechTalk.SpecFlow.TestRunner.CollectScenarioErrors()
   at Project.Specs.LoginFeature.ScenarioCleanup()
   at Project.Specs.LoginFeature.LogInAsAdmin() in C:\Working\dev\Project.Specs\Login.feature:line 14
Result Message: 
Test method Project.Specs.LoginFeature.LogInAsAdmin threw exception: 
SpecBind.Pages.PageNavigationException: Browser did not resolve to the 'HomePage' page in 00:00:10
```

**Standard Output**

```
Test Name:  LogInAsAdmin
Test Outcome:   Failed
Result Message: 
Test method Project.Specs.LoginFeature.LogInAsAdmin threw exception: 
SpecBind.Pages.PageNavigationException: Browser did not resolve to the 'HomePage' page in 00:00:10
Result StandardOutput:  
Given I navigated to the Index page
SpecBind Debug: Navigation action detected, checking for cookie...
SpecBind Debug: Navigating to page: Index (Project.Specs.IndexPage)
Application Base URI: http://localhost/Project
SpecBind Debug: Navigating to URL: http://localhost/Project/index.html
-> done: PageNavigationSteps.GivenNavigateToPageStep("Index") (6.9s)
When I enter data
  --- table step argument ---
  | Field     | Value |
  | User Name | admin |
  | Password  | admin |
-> done: DataSteps.WhenIEnterDataInFieldsStep(<table>) (1.7s)
And I choose Login
-> done: SelectionSteps.WhenIChooseALinkStep("Login") (1.0s)
And I wait 10 seconds for the Dashboard page
-> error: Browser did not resolve to the 'HomePage' page in 00:00:10
Then I am on the Dashboard page
-> skipped because of previous errors
Created Error Screenshot: C:\Working\dev\Project\TestResults\username_hostname 2016-06-03 13_25_07\Out\error_Login_LogInAsAdmin_20160603_132528.jpg
```

The next time I run the test (or if change that step to `And I wait for the Dashboard page` and then re-ran the test), that's when I get the `UITestException: The Coded UI Test is running in Single Thread Apartment (STA) mode of COM. In this mode, all the playback calls should happen from the TestMethod thread only and UITestControl should not be shared across TestMethods.` exception.

In order to get the test run back to normal, I have to kill `w3wp.exe` that is hosting my web application. The next time the test runs it takes a little longer to load up the pages so it may be a timing issue and/or a cleanup issue. :confused:

**Comment by icnocop** [comment]
Fixed in https://github.com/dpiessens/specbind/commit/10d1f68efcb3e2ac98ee6d0d6ef63823d63ef385
