### ISSUE TITLE
How to verify/validate radio button's Selected state?

### ISSUE THREAD

**Issue by icnocop** [dpiessens/specbind#115]
I can successfully automate selecting a radio button as follows:
```
[ElementLocator(Name = "radioButtonInputName", Value = "radioButtonInputValue")]
public HtmlRadioButton MyRadioButton { get; set; }
```

```
Given I entered data
     | Field           | Value |
     | My Radio Button | True  |
```
But how do I verify/validate a radio button is selected?

If I try to use the following:
```
Then I see
     | Field           | Rule   | Value |
     | My Radio Button | Equals | True  |
```
I get an exception:
```
Result StackTrace:	
at SpecBind.ActionPipeline.ActionResultExtensions.CheckActionResult(ActionResult result)
   at SpecBind.ActionPipeline.ActionResultExtensions.CheckResult(ActionResult result)
   at SpecBind.DataSteps.ThenISeeStep(Table data)
   at lambda_method(Closure , IContextManager , Table )
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at TechTalk.SpecFlow.TestRunner.CollectScenarioErrors()
   at MySpecs.ConfigurationFeature.ScenarioCleanup()
   at MySpecs.ConfigurationFeature.SaveGeneralConfiguration() in C:\Working\dev\MySpecs\MyFeature.feature:line 32
Result Message:	
Test method MySpecs.MyFeature.MyScenario threw exception: 
SpecBind.Pages.ElementExecuteException: Value comparison(s) failed. See details for validation results.
| Field           | Rule   | Value          |
| My Radio Button | Equals | True [<EMPTY>] |
```

Thank you.

**Comment by icnocop** [comment]
It seems this is a manual process and I have to create a property in my Page/HtmlDocument.

For example:
```
        [ElementLocator(Name = "RadioButtonGroupName", Value = "RadioButton1Value")]
        public HtmlRadioButton RadioButton1 { get; set; }

        [ElementLocator(Name = "RadioButtonGroupName", Value = "RadioButton2Value")]
        public HtmlRadioButton RadioButton2 { get; set; }

        public string RadioButtonGroupName
        {
            get
            {
                if (this.RadioButton1.Selected)
                {
                    return this.RadioButton1.Value;
                }
                else if (this.RadioButton2.Selected)
                {
                    return this.RadioButton2.Value;
                }
                else
                {
                    return null;
                }
            }
        }
```

And then I can do the following:
```
Then I see
     | Field                | Rule   | Value             |
     | RadioButtonGroupName | Equals | RadioButton1Value |
```
