### ISSUE TITLE
Highlighting an item is not suppported by property type 'ListPropertyData`1'

### ISSUE THREAD

**Issue by ramiabughazaleh** [dpiessens/specbind#127]
Running a test with HighlightMode enabled fails if the test searches for list elements.

**Steps to reproduce:**
1. Edit .\examples\FullDemo\ContosoUniversity.AcceptanceTests\App.config:
Add
```
  <appSettings>
    <add key="HighlightMode" value="true" />
  </appSettings>
```
2. Run the test FindPeggyJusticeByHerFirstName

**Expected:**
Test Outcome: Passed

**Actual:**
Test Outcome:	Failed

Result Message:
```
Test method ContosoUniversity.AcceptanceTests.Scenarios.SearchForAStudentByNameFeature.FindPeggyJusticeByHerFirstName threw exception: 
System.NotSupportedException: Highlighting an item is not suppported by property type 'ListPropertyData`1'
Result StackTrace:	
at SpecBind.ActionPipeline.ActionResultExtensions.CheckActionResult(ActionResult result)
   at SpecBind.DataSteps.ThenISeeListStep(String fieldName, String rule, Table data)
   at lambda_method(Closure , IContextManager , String , String , Table )
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at TechTalk.SpecFlow.TestRunner.CollectScenarioErrors()
   at ContosoUniversity.AcceptanceTests.Scenarios.SearchForAStudentByNameFeature.ScenarioCleanup() in c:\github\dpiessens\specbind\examples\FullDemo\ContosoUniversity.AcceptanceTests\Scenarios\SearchForAStudent.feature.cs:line 0
   at ContosoUniversity.AcceptanceTests.Scenarios.SearchForAStudentByNameFeature.FindPeggyJusticeByHerFirstName() in c:\github\dpiessens\specbind\examples\FullDemo\ContosoUniversity.AcceptanceTests\Scenarios\SearchForAStudent.feature:line 14
```

**Comment by dpiessens** [comment]
This has been fixed in SpecBind 2.0
