### ISSUE TITLE
Development and Runtime Requirements Wiki?

### ISSUE THREAD

**Issue by icnocop** [dpiessens/specbind#137]
Hi.

It seems with the latest changes, Visual Studio 2017 is required in order to build SpecBind from the source code.

It also seems that Visual Studio 2017 is required in order to run SpecBind tests with Microsoft's CodedUI.

In previous builds, only Visual Studio 2015 was required.

So I'm thinking that one or more wiki pages should be created to indicate the development and runtime requirements for SpecBind.

For example, when I try to build the SpecBind solution from the latest source code in Visual Studio 2015, I get the following errors:
```
1>------ Build started: Project: SpecBind.CodedUI, Configuration: Debug Any CPU ------
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUIBrowser.cs(15,21,15,33): error CS0234: The type or namespace name 'VisualStudio' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUIBrowser.cs(16,21,16,33): error CS0234: The type or namespace name 'VisualStudio' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUIBrowser.cs(17,21,17,33): error CS0234: The type or namespace name 'VisualStudio' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUIBrowserFactory.cs(9,18,9,30): error CS0234: The type or namespace name 'VisualStudio' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUIBrowserFactory.cs(10,18,10,30): error CS0234: The type or namespace name 'VisualStudio' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUIListElementWrapper.cs(10,18,10,30): error CS0234: The type or namespace name 'VisualStudio' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUIListElementWrapper.cs(11,18,11,30): error CS0234: The type or namespace name 'VisualStudio' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUIPage.cs(13,18,13,30): error CS0234: The type or namespace name 'VisualStudio' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUIPage.cs(14,18,14,30): error CS0234: The type or namespace name 'VisualStudio' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUIPage.cs(15,18,15,30): error CS0234: The type or namespace name 'VisualStudio' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUITableDriver.cs(9,21,9,33): error CS0234: The type or namespace name 'VisualStudio' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUITableDriver.cs(10,21,10,33): error CS0234: The type or namespace name 'VisualStudio' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\PageBuilder.cs(10,18,10,30): error CS0234: The type or namespace name 'VisualStudio' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\PageBuilder.cs(11,18,11,30): error CS0234: The type or namespace name 'VisualStudio' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUIListElementWrapper.cs(23,20,23,33): error CS0246: The type or namespace name 'UITestControl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUIListElementWrapper.cs(24,25,24,36): error CS0246: The type or namespace name 'HtmlControl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUIListElementWrapper.cs(112,48,112,61): error CS0246: The type or namespace name 'UITestControl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUIListElementWrapper.cs(126,76,126,89): error CS0246: The type or namespace name 'UITestControl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUIPage.cs(26,60,26,71): error CS0246: The type or namespace name 'HtmlControl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUIListElementWrapper.cs(26,52,26,63): error CS0246: The type or namespace name 'HtmlControl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUITableDriver.cs(20,65,20,74): error CS0246: The type or namespace name 'HtmlTable' could not be found (are you missing a using directive or an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUIPage.cs(56,37,56,48): error CS0246: The type or namespace name 'HtmlControl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUIPage.cs(68,42,68,53): error CS0246: The type or namespace name 'HtmlControl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUIPage.cs(94,44,94,55): error CS0246: The type or namespace name 'HtmlControl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUIPage.cs(105,49,105,60): error CS0246: The type or namespace name 'HtmlControl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUIPage.cs(122,52,122,63): error CS0246: The type or namespace name 'HtmlControl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUIPage.cs(138,54,138,65): error CS0246: The type or namespace name 'HtmlControl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUIPage.cs(149,41,149,52): error CS0246: The type or namespace name 'HtmlControl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUIPage.cs(177,44,177,55): error CS0246: The type or namespace name 'HtmlControl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUIPage.cs(187,37,187,48): error CS0246: The type or namespace name 'HtmlControl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUIBrowser.cs(336,17,336,29): error CS0246: The type or namespace name 'HtmlDocument' could not be found (are you missing a using directive or an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUIBrowser.cs(390,48,390,61): error CS0246: The type or namespace name 'UITestControl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUIBrowser.cs(390,63,390,72): error CS0246: The type or namespace name 'HtmlFrame' could not be found (are you missing a using directive or an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUIBrowser.cs(30,55,30,68): error CS0246: The type or namespace name 'UITestControl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUIBrowser.cs(30,70,30,79): error CS0246: The type or namespace name 'HtmlFrame' could not be found (are you missing a using directive or an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUIBrowser.cs(32,48,32,61): error CS0246: The type or namespace name 'UITestControl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUIBrowser.cs(32,80,32,91): error CS0246: The type or namespace name 'HtmlControl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUIBrowser.cs(32,94,32,106): error CS0246: The type or namespace name 'HtmlDocument' could not be found (are you missing a using directive or an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUIBrowser.cs(34,31,34,44): error CS0246: The type or namespace name 'BrowserWindow' could not be found (are you missing a using directive or an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUIBrowser.cs(41,36,41,49): error CS0246: The type or namespace name 'BrowserWindow' could not be found (are you missing a using directive or an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\PageBuilder.cs(22,66,22,79): error CS0246: The type or namespace name 'UITestControl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\PageBuilder.cs(22,90,22,101): error CS0246: The type or namespace name 'HtmlControl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\PageBuilder.cs(23,25,23,38): error CS0246: The type or namespace name 'UITestControl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\PageBuilder.cs(24,25,24,36): error CS0246: The type or namespace name 'HtmlControl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUIPage.cs(208,26,208,37): error CS0246: The type or namespace name 'HtmlControl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUIPage.cs(219,26,219,37): error CS0246: The type or namespace name 'HtmlControl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUIPage.cs(333,39,333,52): error CS0246: The type or namespace name 'UITestControl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUITableDriver.cs(20,18,20,36): error CS0311: The type 'SpecBind.CodedUI.CodedUITableDriver.RowWrapper' cannot be used as type parameter 'TChildElement' in the generic type or method 'CodedUIListElementWrapper<TElement, TChildElement>'. There is no implicit reference conversion from 'SpecBind.CodedUI.CodedUITableDriver.RowWrapper' to 'HtmlControl'.
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUITableDriver.cs(49,62,49,71): error CS0246: The type or namespace name 'HtmlTable' could not be found (are you missing a using directive or an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUITableDriver.cs(27,35,27,44): error CS0246: The type or namespace name 'HtmlTable' could not be found (are you missing a using directive or an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUITableDriver.cs(73,35,73,42): error CS0246: The type or namespace name 'HtmlRow' could not be found (are you missing a using directive or an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\PageBuilder.cs(22,18,22,29): error CS0452: The type 'TOutput' must be a reference type in order to use it as parameter 'TOutput' in the generic type or method 'PageBuilderBase<TParent, TOutput, TElement>'
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUITableDriver.cs(75,30,75,39): error CS0246: The type or namespace name 'HtmlTable' could not be found (are you missing a using directive or an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\CodedUITableDriver.cs(81,31,81,44): error CS0246: The type or namespace name 'UITestControl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\PageBuilder.cs(32,54,32,65): error CS0246: The type or namespace name 'HtmlControl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\PageBuilder.cs(56,57,56,68): error CS0246: The type or namespace name 'HtmlControl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\PageBuilder.cs(141,38,141,51): error CS0246: The type or namespace name 'UITestControl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\PageBuilder.cs(171,35,171,63): error CS0246: The type or namespace name 'PropertyExpressionCollection' could not be found (are you missing a using directive or an assembly reference?)
1>C:\github\dpiessens\specbind\src\SpecBind.CodedUI\PageBuilder.cs(183,61,183,89): error CS0246: The type or namespace name 'PropertyExpressionCollection' could not be found (are you missing a using directive or an assembly reference?)
2>------ Build started: Project: SpecBind.Selenium, Configuration: Debug Any CPU ------
2>  All packages listed in packages.config are already installed.
2>C:\github\dpiessens\specbind\src\SpecBind.Selenium\SeleniumBrowserFactory.cs(70,103,70,109): error CS1003: Syntax error, ',' expected
2>C:\github\dpiessens\specbind\src\SpecBind.Selenium\SeleniumBrowserFactory.cs(348,70,348,73): error CS1525: Invalid expression term 'int'
2>C:\github\dpiessens\specbind\src\SpecBind.Selenium\SeleniumBrowserFactory.cs(348,74,348,82): error CS1003: Syntax error, ',' expected
2>C:\github\dpiessens\specbind\src\SpecBind.Selenium\SeleniumBrowserFactory.cs(353,76,353,80): error CS1525: Invalid expression term 'bool'
2>C:\github\dpiessens\specbind\src\SpecBind.Selenium\SeleniumBrowserFactory.cs(353,81,353,90): error CS1003: Syntax error, ',' expected
2>C:\github\dpiessens\specbind\src\SpecBind.Selenium\SeleniumBrowserFactory.cs(395,79,395,88): error CS1003: Syntax error, ',' expected

```

Also for example, when I to run a BDD test using SpecBind 2.0.0.309 in Visual Studio 2013, with Visual Studio 2015 installed, but without Visual Studio 2017 installed, I get the following error:

```
Test Name:	FindPeggyJusticeByHerFirstName
Test FullName:	ContosoUniversity.AcceptanceTests.Scenarios.SearchForAStudentByNameFeature.FindPeggyJusticeByHerFirstName
Test Source:	c:\github\dpiessens\specbind\examples\FullDemo\ContosoUniversity.AcceptanceTests\Scenarios\SearchForAStudent.feature : line 6
Test Outcome:	Failed
Test Duration:	0:00:00.5060836

Result Message:	
Test method ContosoUniversity.AcceptanceTests.Scenarios.SearchForAStudentByNameFeature.FindPeggyJusticeByHerFirstName threw exception: 
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.TestTools.UITest.Extension, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
Result StackTrace:	
at SpecBind.CodedUI.CodedUIBrowserFactory.CreateBrowser(BrowserType browserType, BrowserFactoryConfigurationElement browserFactoryConfiguration, ILogger logger)
   at SpecBind.BrowserSupport.BrowserFactory.LoadConfigurationAndCreateBrowser(Func`4 createMethod)
   at SpecBind.BrowserSupport.BrowserFactory.GetBrowser()
   at SpecBind.BrowserSupport.WebDriverSupport.InitializeDriver()
   at SpecBind.BrowserSupport.WebDriverSupport.BeforeScenario()
   at lambda_method(Closure , IContextManager )
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.InvokeHook(IBindingInvoker invoker, IHookBinding hookBinding, HookType hookType)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.FireEvents(HookType hookType)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.FireScenarioEvents(HookType bindingEvent)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnScenarioStart(ScenarioInfo scenarioInfo)
   at TechTalk.SpecFlow.TestRunner.OnScenarioStart(ScenarioInfo scenarioInfo)
   at ContosoUniversity.AcceptanceTests.Scenarios.SearchForAStudentByNameFeature.ScenarioSetup(ScenarioInfo scenarioInfo) in c:\github\dpiessens\specbind\examples\FullDemo\ContosoUniversity.AcceptanceTests\Scenarios\SearchForAStudent.feature.cs:line 0
   at ContosoUniversity.AcceptanceTests.Scenarios.SearchForAStudentByNameFeature.FindPeggyJusticeByHerFirstName() in c:\github\dpiessens\specbind\examples\FullDemo\ContosoUniversity.AcceptanceTests\Scenarios\SearchForAStudent.feature:line 6
```

Thank you.

**Comment by icnocop** [comment]
StyleCop 4.7 also seems to be a requirement, as referenced from SpecBind.csproj:
```
<Import Project="$(MSBuildExtensionsPath32)\StyleCop\v4.7\StyleCop.targets" Condition="Exists('$(MSBuildExtensionsPath32)\StyleCop\v4.7\StyleCop.targets')" />
```
