### ISSUE TITLE
Equals comparer/validation rule doesn't actually support a boolean property

### ISSUE THREAD

**Issue by icnocop** [dpiessens/specbind#158]
Hi.

For example, add the following scenario in `.\src\SpecBind.Selenium.IntegrationTests\Features\ValidationTests.feature`
```
Scenario: Validate Boolean Property
	 Given I navigated to the Home page
	 Then I see
		| Field | Rule   | Value |
		| Test  | Equals | true  |
```

Add the following in `\src\specbind.selenium.integrationtests\pages\homepage.cs`
```
        public bool Test
        {
            get
            {
                return true;
            }
        }
```

When you run the `ValidateBooleanProperty` test, it fails with the following:

```
Result Message:	
Test method SpecBind.Selenium.IntegrationTests.Features.ValidationFeaturesFeature.ValidateBooleanProperty threw exception: 
SpecBind.Pages.ElementExecuteException: Value comparison(s) failed. See details for validation results.
| Field            | Rule   | Value |
| Test [Not Found] | Equals | true  |

Result StackTrace:	
at SpecBind.ActionPipeline.ActionResultExtensions.CheckActionResult(ActionResult result) in C:\github\dpiessens\specbind\src\SpecBind\ActionPipeline\ActionResultExtensions.cs:line 46
   at SpecBind.ActionPipeline.ActionResultExtensions.CheckResult(ActionResult result) in C:\github\dpiessens\specbind\src\SpecBind\ActionPipeline\ActionResultExtensions.cs:line 29
   at SpecBind.DataSteps.ThenISeeStep(Table data) in C:\github\dpiessens\specbind\src\SpecBind\DataSteps.cs:line 155
   at lambda_method(Closure , IContextManager , Table )
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(IContextManager contextManager, StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at TechTalk.SpecFlow.TestRunner.CollectScenarioErrors()
   at SpecBind.Selenium.IntegrationTests.Features.ValidationFeaturesFeature.ScenarioCleanup()
   at SpecBind.Selenium.IntegrationTests.Features.ValidationFeaturesFeature.ValidateBooleanProperty() in C:\github\dpiessens\specbind\src\SpecBind.Selenium.IntegrationTests\Features\ValidationTests.feature:line 117
```

It works without issues if the property is a string:
```
        public string Test
        {
            get
            {
                return "true";
            }
        }
```

Thank you.

**Comment by dpiessens** [comment]
Properties that are not text are not supported, read only properties were only meant to be helpers to get to complex properties on an object.

**Comment by icnocop** [comment]
Should the documentation in https://github.com/dpiessens/specbind/wiki/Verifying-Steps be updated accordingly?

It lists `Boolean` in the list.

Also, that wiki page reads `The fields are checked in the order defined by in the table.` which has a grammatical error.

Thank you.
