### ISSUE TITLE
Ability to capture JavaScript errors

### ISSUE THREAD

**Issue by icnocop** [dpiessens/specbind#176]
Hi.

I'd like the ability to capture JavaScript errors.

If I call the `ExecuteScript` method on the instance of `SeleniumBrowser` a JavaScript error could be produced.

This will throw an exception, but not a very detailed one:
```
System.InvalidOperationException: JavaScript error (UnexpectedJavaScriptError)
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.ExecuteScriptCommand(String script, String commandName, Object[] args)
   at OpenQA.Selenium.Remote.RemoteWebDriver.ExecuteScript(String script, Object[] args)
   at SpecBind.Selenium.SeleniumBrowser.ExecuteScript(String script, Object[] args) ...
```

I expected to see the actual JavaScript error in the exception for example.

Another use case is the ability to validate that navigating to a page doesn't produce any JavaScript errors.
Or maybe validating that an action on a page also doesn't produce any JavaScript errors.

I'm thinking this can be done by getting the browser console logs.

For example:
```
// Chrome
ChromeOptions options = new ChromeOptions();
options.SetLoggingPreference(LogType.Browser, LogLevel.All);

// Firefox
FirefoxOptions options = new FirefoxOptions();
options.SetLoggingPreference(LogType.Browser, LogLevel.All);

// Get logs
List<LogEntry> logs = driver.Manage().Logs.GetLog(LogType.Browser).ToList();
```

Thoughts?

Thank you.

**Comment by icnocop** [comment]
Another approach could be to inject some JavaScript code to capture errors:
http://jimevansmusic.blogspot.com/2013/09/capturing-javascript-errors-in.html
